pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package install'
            }
        }
        stage('Deploy') {
            steps {
                def tc9 = tomcat9( 
                    url:        'http://192.168.0.100:8088',
                    password:   'cattom', 
                    userName:   'tomcat'
                )
                deploy(adapters: tc9, war: '**/*.war', contextPath: '/helloworld')                
            }
        }        
    }
}
