pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package install'
            }
        }
        stage('Deploy') {
            steps {
                deploy adapters: [tomcat9(credentialsId: '0d8b3ad0-e6d1-49d5-b36f-569619f72c10', path: '', url: "http://192.168.0.100:8088/hwd")], war: '**/*.war', contextPath: 'helloworld' 
            }
        }        
    }
}
